var titleKeywords = {
    "visualization": "visualization",
    "visualizing": "visualization",
    "charting": "visualization",
    "information visualization": "information visualization",
    "graph visualization" : "information visualization",
    "network visualization" : "information visualization",
    "network layout": "information visualization",
    "parallel coordinates": "information visualization",
    "node-link": "information visualization",
    "treemap" : "information visualization",
    "flow visualization": "scientific visualization",
    "visual analytics": "visual analytics",
    "raycasting": "computer graphics",
    "rendering": "computer graphics",
    "human-computer": "human-computer interaction",
    "human computer": "human-computer interaction",
    "human-machine": "human-computer interaction",
    "hci": "human-computer interaction",
    "user interface": "human-computer interaction",
    "biomedical": "bioinformatics",
    "health record": "bioinformatics",
};